name: CI

on:
  member: 
  push:
    branches:
    - master
  schedule:
  - cron: "0 9 * * *"

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Rspec
      env: 
        SHODAN_API_KEY: ${{secrets.SHODAN_API_KEY}}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
        
